baseURL = 'https://chateau-laubardemont.com'
languageCode = 'en-us'
title = 'Laubardemont'



[mediaTypes]
  [mediaTypes."application/x-php"]
  suffixes = ["php"]

[outputFormats]
  [outputFormats.PHP]
    mediaType = "application/x-php"
    isPlainText = true
    baseName = "index"



[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"




